export interface CompanyInfo {
  id: string;
  organization_code: string;
  name: string;
  establishment_date: string;
  headoffice_postalcode: string;
  headoffice_address: string;
  representative_name: string;
  capital: string;
  num_of_employees: string;
  business_details: string;
  main_client: string;
  telephone_number: string;
  fax_number: string;
  email: string;
  website: string;
  corporate_number: string;
  office_number: string;
  trading_account: string;
  registration_number: string;
  registration_date: string;
  validity_period: string;
  online_application_id: string;
  online_application_pass: string;
  application_agent_certificate: string;
  service_type: string;
  plan_start_date: string;
  specified_validity_period: string;
}
